# Generated by Django 4.0.3 on 2022-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_car_object_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
